### ISSUE TITLE
Cached SSO login is expired/invalid, try running `aws sso login` and try again error with latest version of AWS CLI 2.9.4

### ISSUE THREAD

**Issue by rutomo** [ryansonshine/aws-sso-creds-helper#59]
## Current Behavior
With latest version of AWS CLI 2.9.4, running `ssocreds -p default` failed due to a change of structure in `~/.aws/config` when a user specifies `SSO session name (Recommended):` during `aws configure sso` process
```
ssocreds -p <profile_name>                                                                                                
[aws-sso-creds-helper]: AWS SSO Creds Helper v1.9.0
[aws-sso-creds-helper]: Getting SSO credentials for profile <profile_name>
[aws-sso-creds-helper]: Failed to load SSO credentials for <profile_name>
[aws-sso-creds-helper]: Cached SSO login is expired/invalid, try running `aws sso login` and try again
[aws-sso-creds-helper]: Run ssocreds with --debug flag for more details.
```

## Expected Behavior
```
ssocreds -p <profile_name> 
[aws-sso-creds-helper]: AWS SSO Creds Helper v1.9.0
[aws-sso-creds-helper]: Getting SSO credentials for profile <profile_name>
[aws-sso-creds-helper]: Successfully loaded SSO credentials for profile <profile_name>
```
## Steps to Reproduce the Problem

  1. Install latest version of AWS CLI (2.9.4 was the latest at the time this writing)
  1. Run `aws configure sso --profile <profile_name>`
  1. Populate `SSO session name (Recommended)` when it asks
  2. Follow rest of configuration process
  3. Run `ssocreds -p <profile_name> `
  4. You'd get the error I mentioned above.

The current workaround is to leave `SSO session name (Recommended)` blank during configuration process to default to previous behaviour.

## Environment

- Version: 1.9.0
- Platform: Mac
- Node.js Version: v16.18.1

**Comment by ryansonshine** [comment]
@rutomo , thanks for contributing!

I'm unable to reproduce this with the versions you provided. Can you please re-run with the `--debug` flag and post the output with sensitive data removed?

Thanks!

**Comment by diogobaltazar** [comment]
I have the exact same problem. Running stdout for ``--debug``:

```shell
npx ssocreds -p PRF --debug
[aws-sso-creds-helper]: AWS SSO Creds Helper v1.9.0
[aws-sso-creds-helper]: ===========
[aws-sso-creds-helper]: SYSTEM INFO
[aws-sso-creds-helper]: ===========
[aws-sso-creds-helper]: AWS CLI Version aws-cli/2.9.6 Python/3.9.11 Linux/5.10.16.3-microsoft-standard-WSL2 exe/x86_64.ubuntu.20 prompt/off
[aws-sso-creds-helper]: OS linux 5.10.16.3-microsoft-standard-WSL2
[aws-sso-creds-helper]: Node v19.2.0
[aws-sso-creds-helper]: ==============
[aws-sso-creds-helper]: PROFILE CONFIG
[aws-sso-creds-helper]: ==============
[aws-sso-creds-helper]: 
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                     PRF            manual    --profile
access_key     ****************T6MJ              sso    
secret_key     ****************ggfb              sso    
    region             eu-central-1      config-file    ~/.aws/config

[aws-sso-creds-helper]: Getting SSO credentials for profile PRF
[aws-sso-creds-helper]: Reading config from /home/USR/.aws/config
[aws-sso-creds-helper]: Full profile name for lookup is profile PRF
[aws-sso-creds-helper]: Profile data:, {
  "sso_session": "SSOORG",
  "sso_account_id": "ACC_ID",
  "sso_role_name": "ROLE",
  "region": "eu-central-1",
  "output": "json"
}
[aws-sso-creds-helper]: Setting AWS.SharedIniFileCredentials to profile PRF
[aws-sso-creds-helper]: Found 5 cache files in /home/USR/.aws/sso/cache:
642afec8d3750b2716d42752fed8efe0ea1b91d4.json
65af64f609f482bdf3eed7abc365b61ce1fa1c9b.json
82b9ea8166846ac0ee16eb19648a7690c7d2035d.json
beb6c4dee665a0f8138d720343c977f081b24a99.json
d4e79740b7cf784988cd19af4057801aa7cabfa7.json
[aws-sso-creds-helper]: Checking 642afec8d3750b2716d42752fed8efe0ea1b91d4.json in /home/USR/.aws/sso/cache/642afec8d3750b2716d42752fed8efe0ea1b91d4.json
[aws-sso-creds-helper]: Reading /home/USR/.aws/sso/cache/642afec8d3750b2716d42752fed8efe0ea1b91d4.json
[aws-sso-creds-helper]: Configuration is NOT a credential config
[aws-sso-creds-helper]: Checking 65af64f609f482bdf3eed7abc365b61ce1fa1c9b.json in /home/USR/.aws/sso/cache/65af64f609f482bdf3eed7abc365b61ce1fa1c9b.json
[aws-sso-creds-helper]: Reading /home/USR/.aws/sso/cache/65af64f609f482bdf3eed7abc365b61ce1fa1c9b.json
[aws-sso-creds-helper]: Configuration is NOT a credential config
[aws-sso-creds-helper]: Checking 82b9ea8166846ac0ee16eb19648a7690c7d2035d.json in /home/USR/.aws/sso/cache/82b9ea8166846ac0ee16eb19648a7690c7d2035d.json
[aws-sso-creds-helper]: Reading /home/USR/.aws/sso/cache/82b9ea8166846ac0ee16eb19648a7690c7d2035d.json
[aws-sso-creds-helper]: Configuration is a credential config
[aws-sso-creds-helper]: Credential is expired
[aws-sso-creds-helper]: Checking beb6c4dee665a0f8138d720343c977f081b24a99.json in /home/USR/.aws/sso/cache/beb6c4dee665a0f8138d720343c977f081b24a99.json
[aws-sso-creds-helper]: Reading /home/USR/.aws/sso/cache/beb6c4dee665a0f8138d720343c977f081b24a99.json
[aws-sso-creds-helper]: Configuration is NOT a credential config
[aws-sso-creds-helper]: Checking d4e79740b7cf784988cd19af4057801aa7cabfa7.json in /home/USR/.aws/sso/cache/d4e79740b7cf784988cd19af4057801aa7cabfa7.json
[aws-sso-creds-helper]: Reading /home/USR/.aws/sso/cache/d4e79740b7cf784988cd19af4057801aa7cabfa7.json
[aws-sso-creds-helper]: Configuration is a credential config
[aws-sso-creds-helper]: Credential is NOT expired
[aws-sso-creds-helper]: Error is an ExpiredCredsError
[aws-sso-creds-helper]: Failed on first pass to get credentials, incrementing failed attempts and trying again
[aws-sso-creds-helper]: Executing command aws sso login --profile PRF
[aws-sso-creds-helper]: Received callback from running aws sso login --profile PRF
[aws-sso-creds-helper]: Reading config from /home/USR/.aws/config
[aws-sso-creds-helper]: Full profile name for lookup is profile PRF
[aws-sso-creds-helper]: Profile data:, {
  "sso_session": "SSOORG",
  "sso_account_id": "ACC_ID",
  "sso_role_name": "ROLE",
  "region": "eu-central-1",
  "output": "json"
}
[aws-sso-creds-helper]: Setting AWS.SharedIniFileCredentials to profile PRF
[aws-sso-creds-helper]: Found 5 cache files in /home/USR/.aws/sso/cache:
642afec8d3750b2716d42752fed8efe0ea1b91d4.json
65af64f609f482bdf3eed7abc365b61ce1fa1c9b.json
82b9ea8166846ac0ee16eb19648a7690c7d2035d.json
beb6c4dee665a0f8138d720343c977f081b24a99.json
d4e79740b7cf784988cd19af4057801aa7cabfa7.json
[aws-sso-creds-helper]: Checking 642afec8d3750b2716d42752fed8efe0ea1b91d4.json in /home/USR/.aws/sso/cache/642afec8d3750b2716d42752fed8efe0ea1b91d4.json
[aws-sso-creds-helper]: Reading /home/USR/.aws/sso/cache/642afec8d3750b2716d42752fed8efe0ea1b91d4.json
[aws-sso-creds-helper]: Configuration is NOT a credential config
[aws-sso-creds-helper]: Checking 65af64f609f482bdf3eed7abc365b61ce1fa1c9b.json in /home/USR/.aws/sso/cache/65af64f609f482bdf3eed7abc365b61ce1fa1c9b.json
[aws-sso-creds-helper]: Reading /home/USR/.aws/sso/cache/65af64f609f482bdf3eed7abc365b61ce1fa1c9b.json
[aws-sso-creds-helper]: Configuration is NOT a credential config
[aws-sso-creds-helper]: Checking 82b9ea8166846ac0ee16eb19648a7690c7d2035d.json in /home/USR/.aws/sso/cache/82b9ea8166846ac0ee16eb19648a7690c7d2035d.json
[aws-sso-creds-helper]: Reading /home/USR/.aws/sso/cache/82b9ea8166846ac0ee16eb19648a7690c7d2035d.json
[aws-sso-creds-helper]: Configuration is a credential config
[aws-sso-creds-helper]: Credential is expired
[aws-sso-creds-helper]: Checking beb6c4dee665a0f8138d720343c977f081b24a99.json in /home/USR/.aws/sso/cache/beb6c4dee665a0f8138d720343c977f081b24a99.json
[aws-sso-creds-helper]: Reading /home/USR/.aws/sso/cache/beb6c4dee665a0f8138d720343c977f081b24a99.json
[aws-sso-creds-helper]: Configuration is NOT a credential config
[aws-sso-creds-helper]: Checking d4e79740b7cf784988cd19af4057801aa7cabfa7.json in /home/USR/.aws/sso/cache/d4e79740b7cf784988cd19af4057801aa7cabfa7.json
[aws-sso-creds-helper]: Reading /home/USR/.aws/sso/cache/d4e79740b7cf784988cd19af4057801aa7cabfa7.json
[aws-sso-creds-helper]: Configuration is a credential config
[aws-sso-creds-helper]: Credential is NOT expired
[aws-sso-creds-helper]: Error is an ExpiredCredsError
[aws-sso-creds-helper]: Failed to load SSO credentials for PRF
[aws-sso-creds-helper]: Cached SSO login is expired/invalid, try running `aws sso login` and try again
[aws-sso-creds-helper]: ExpiredCredsError: Cached SSO login is expired/invalid, try running `aws sso login` and try again
    at exports.getSsoCachedLogin (/home/USR/arteklabs/template-aws-cdk/node_modules/aws-sso-creds-helper/lib/sso-creds.js:41:11)
    at /home/USR/arteklabs/template-aws-cdk/node_modules/aws-sso-creds-helper/lib/sso-creds.js:94:37
    at Generator.next (<anonymous>)
    at /home/USR/arteklabs/template-aws-cdk/node_modules/aws-sso-creds-helper/lib/sso-creds.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/USR/arteklabs/template-aws-cdk/node_modules/aws-sso-creds-helper/lib/sso-creds.js:4:12)
    at exports.run (/home/USR/arteklabs/template-aws-cdk/node_modules/aws-sso-creds-helper/lib/sso-creds.js:91:59)
    at /home/USR/arteklabs/template-aws-cdk/node_modules/aws-sso-creds-helper/lib/sso-creds.js:103:27
    at Generator.next (<anonymous>)
    at fulfilled (/home/USR/arteklabs/template-aws-cdk/node_modules/aws-sso-creds-helper/lib/sso-creds.js:5:58)
```

**Comment by diogobaltazar** [comment]
After reverting from

```shell
[profile PRF]
sso_session = SSOPORTAL
sso_account_id = ACC_ID
sso_role_name = ROLE
region = eu-central-1
output = json

[sso-session SSOPORTAL]
sso_start_url = https://SSOPORTAL.awsapps.com/start/
sso_region = eu-central-1
sso_registration_scopes = sso:account:access
```
to

```shell
[profile PRF]
sso_start_url = https://SSOPORTAL.awsapps.com/start/
sso_region = eu-central-1
sso_session = SSOPORTAL
sso_account_id = ACC_ID
sso_role_name = ROLE
region = eu-central-1
output = json
```

the tool works as expected:

```shell
npx ssocreds -p PRF
[aws-sso-creds-helper]: AWS SSO Creds Helper v1.9.0
[aws-sso-creds-helper]: Getting SSO credentials for profile PRF
[aws-sso-creds-helper]: Successfully loaded SSO credentials for profile PRF
```

**Comment by diogobaltazar** [comment]
@rutomo you can fix your issue by reformatting ``.aws/config`` to the previous SSO format, feel free to reach out in this chat if you'd like assistance with that.

**Comment by rutomo** [comment]
The issue only happened when these two conditions are met:
1. During aws sso profile configuration (`aws configure sso`), one of steps asks the user for the session name `SSO session name (Recommended)` and the user provided a session name
2. It's a brand new profile i.e. no existing aws profile with same name in `~/.aws/config`

When these two conditions are met, the `~/.aws/config` will look like below
```
[profile1]
sso_session = profile1
sso_account_id = <aws_account_id>
sso_role_name = <role_name>
region = <region>
output = json
[sso-session profile1]
sso_start_url = https://<sso_portal_id>.awsapps.com/start#/
sso_region = <region>
sso_registration_scopes = sso:account:access
```

When I ran `ssocreds -p profile1`, I got these errors
```
[aws-sso-creds-helper]: AWS SSO Creds Helper v1.9.0
[aws-sso-creds-helper]: Getting SSO credentials for profile default
[aws-sso-creds-helper]: Failed to load SSO credentials for default
[aws-sso-creds-helper]: Cached SSO login is expired/invalid, try running `aws sso login` and try again
[aws-sso-creds-helper]: Run ssocreds with --debug flag for more details.
```

With `ssocreds -p profile1 -- debug`, I got below results
```
[aws-sso-creds-helper]: AWS SSO Creds Helper v1.9.0
[aws-sso-creds-helper]: ===========
[aws-sso-creds-helper]: SYSTEM INFO
[aws-sso-creds-helper]: ===========
[aws-sso-creds-helper]: AWS CLI Version aws-cli/2.9.4 Python/3.9.11 Darwin/21.6.0 exe/x86_64 prompt/off
[aws-sso-creds-helper]: OS darwin 21.6.0
[aws-sso-creds-helper]: Node v16.18.1
[aws-sso-creds-helper]: ==============
[aws-sso-creds-helper]: PROFILE CONFIG
[aws-sso-creds-helper]: ==============
[aws-sso-creds-helper]:
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                  profile1           manual    --profile
access_key               <redacted>              sso
secret_key               <redacted>              sso
    region                <redacted>      config-file    ~/.aws/config

[aws-sso-creds-helper]: Getting SSO credentials for profile profile1
[aws-sso-creds-helper]: Reading config from /Users/user1/.aws/config
[aws-sso-creds-helper]: Full profile name for lookup is profile1
[aws-sso-creds-helper]: Profile data:, {
  "sso_session": "profile1",
  "sso_account_id": "<redacted>",
  "sso_role_name": "<redacted>",
  "region": "<redacted>",
  "output": "json"
}
[aws-sso-creds-helper]: Setting AWS.SharedIniFileCredentials to profile profile1
[aws-sso-creds-helper]: Found 12 cache files in /Users/user1/.aws/sso/cache:
06551ae7a87845b666646ae11673d7c2a1e2d240.json
0d92c2431dc84b346c32051db8c475a0cd0aa25a.json
203f630face956dbe57ecc06395741fe662d446e.json
3711b1163b339a7e9a3ed8108c36a8fcc6d85128.json
4d2d70c5022a0e315c9f33d27fd8aa4961d91645.json
53715388f88dfbbc1adaf48a5486a05293eb368a.json
57fcc8a8b15eb43c6db253035baf19558d3a087d.json
7505d64a54e061b7acd54ccd58b49dc43500b635.json
bf3a5d36eb6fe457a102b08904f83d79b76f92c9.json
botocore-client-id-<redacted>.json
botocore-client-id-<redacted>json
eb12bc71f85121d45077d2d2b6085a6b7815bba9.json
[aws-sso-creds-helper]: Checking 06551ae7a87845b666646ae11673d7c2a1e2d240.json in /Users/user1/.aws/sso/cache/06551ae7a87845b666646ae11673d7c2a1e2d240.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/06551ae7a87845b666646ae11673d7c2a1e2d240.json
[aws-sso-creds-helper]: Configuration is NOT a credential config
[aws-sso-creds-helper]: Checking 0d92c2431dc84b346c32051db8c475a0cd0aa25a.json in /Users/user1/.aws/sso/cache/0d92c2431dc84b346c32051db8c475a0cd0aa25a.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/0d92c2431dc84b346c32051db8c475a0cd0aa25a.json
[aws-sso-creds-helper]: Configuration is a credential config
[aws-sso-creds-helper]: Credential is expired
[aws-sso-creds-helper]: Checking 203f630face956dbe57ecc06395741fe662d446e.json in /Users/user1/.aws/sso/cache/203f630face956dbe57ecc06395741fe662d446e.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/203f630face956dbe57ecc06395741fe662d446e.json
[aws-sso-creds-helper]: Configuration is NOT a credential config
[aws-sso-creds-helper]: Checking 3711b1163b339a7e9a3ed8108c36a8fcc6d85128.json in /Users/user1/.aws/sso/cache/3711b1163b339a7e9a3ed8108c36a8fcc6d85128.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/3711b1163b339a7e9a3ed8108c36a8fcc6d85128.json
[aws-sso-creds-helper]: Configuration is a credential config
[aws-sso-creds-helper]: Credential is expired
[aws-sso-creds-helper]: Checking 4d2d70c5022a0e315c9f33d27fd8aa4961d91645.json in /Users/user1/.aws/sso/cache/4d2d70c5022a0e315c9f33d27fd8aa4961d91645.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/4d2d70c5022a0e315c9f33d27fd8aa4961d91645.json
[aws-sso-creds-helper]: Configuration is a credential config
[aws-sso-creds-helper]: Credential is expired
[aws-sso-creds-helper]: Checking 53715388f88dfbbc1adaf48a5486a05293eb368a.json in /Users/user1/.aws/sso/cache/53715388f88dfbbc1adaf48a5486a05293eb368a.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/53715388f88dfbbc1adaf48a5486a05293eb368a.json
[aws-sso-creds-helper]: Configuration is NOT a credential config
[aws-sso-creds-helper]: Checking 57fcc8a8b15eb43c6db253035baf19558d3a087d.json in /Users/user1/.aws/sso/cache/57fcc8a8b15eb43c6db253035baf19558d3a087d.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/57fcc8a8b15eb43c6db253035baf19558d3a087d.json
[aws-sso-creds-helper]: Configuration is NOT a credential config
[aws-sso-creds-helper]: Checking 7505d64a54e061b7acd54ccd58b49dc43500b635.json in /Users/user1/.aws/sso/cache/7505d64a54e061b7acd54ccd58b49dc43500b635.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/7505d64a54e061b7acd54ccd58b49dc43500b635.json
[aws-sso-creds-helper]: Configuration is a credential config
[aws-sso-creds-helper]: Credential is NOT expired
[aws-sso-creds-helper]: Checking bf3a5d36eb6fe457a102b08904f83d79b76f92c9.json in /Users/user1/.aws/sso/cache/bf3a5d36eb6fe457a102b08904f83d79b76f92c9.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/bf3a5d36eb6fe457a102b08904f83d79b76f92c9.json
[aws-sso-creds-helper]: Configuration is a credential config
[aws-sso-creds-helper]: Credential is expired
[aws-sso-creds-helper]: Checking botocore-client-id-<redacted>.json in /Users/user1/.aws/sso/cache/botocore-client-id-<redacted>.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/botocore-client-id-<redacted>.json
[aws-sso-creds-helper]: Configuration is NOT a credential config
[aws-sso-creds-helper]: Checking botocore-client-id-us-east-1.json in /Users/user1/.aws/sso/cache/botocore-client-id-us-east-1.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/botocore-client-id-us-east-1.json
[aws-sso-creds-helper]: Configuration is NOT a credential config
[aws-sso-creds-helper]: Checking eb12bc71f85121d45077d2d2b6085a6b7815bba9.json in /Users/user1/.aws/sso/cache/eb12bc71f85121d45077d2d2b6085a6b7815bba9.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/eb12bc71f85121d45077d2d2b6085a6b7815bba9.json
[aws-sso-creds-helper]: Configuration is a credential config
[aws-sso-creds-helper]: Credential is expired
[aws-sso-creds-helper]: Error is an ExpiredCredsError
[aws-sso-creds-helper]: Failed on first pass to get credentials, incrementing failed attempts and trying again
[aws-sso-creds-helper]: Executing command aws sso login --profile profile1
[aws-sso-creds-helper]: Received callback from running aws sso login --profile profile1
[aws-sso-creds-helper]: Reading config from /Users/user1/.aws/config
[aws-sso-creds-helper]: Full profile name for lookup is profile1
[aws-sso-creds-helper]: Profile data:, {
  "sso_session": "profile1",
  "sso_account_id": "<redacted>",
  "sso_role_name": "<redacted>",
  "region": "<redacted>",
  "output": "json"
}
[aws-sso-creds-helper]: Setting AWS.SharedIniFileCredentials to profile profile1
[aws-sso-creds-helper]: Found 12 cache files in /Users/user1/.aws/sso/cache:
06551ae7a87845b666646ae11673d7c2a1e2d240.json
0d92c2431dc84b346c32051db8c475a0cd0aa25a.json
203f630face956dbe57ecc06395741fe662d446e.json
3711b1163b339a7e9a3ed8108c36a8fcc6d85128.json
4d2d70c5022a0e315c9f33d27fd8aa4961d91645.json
53715388f88dfbbc1adaf48a5486a05293eb368a.json
57fcc8a8b15eb43c6db253035baf19558d3a087d.json
7505d64a54e061b7acd54ccd58b49dc43500b635.json
bf3a5d36eb6fe457a102b08904f83d79b76f92c9.json
botocore-client-id-<redacted>.json
botocore-client-id-us-east-1.json
eb12bc71f85121d45077d2d2b6085a6b7815bba9.json
[aws-sso-creds-helper]: Checking 06551ae7a87845b666646ae11673d7c2a1e2d240.json in /Users/user1/.aws/sso/cache/06551ae7a87845b666646ae11673d7c2a1e2d240.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/06551ae7a87845b666646ae11673d7c2a1e2d240.json
[aws-sso-creds-helper]: Configuration is NOT a credential config
[aws-sso-creds-helper]: Checking 0d92c2431dc84b346c32051db8c475a0cd0aa25a.json in /Users/user1/.aws/sso/cache/0d92c2431dc84b346c32051db8c475a0cd0aa25a.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/0d92c2431dc84b346c32051db8c475a0cd0aa25a.json
[aws-sso-creds-helper]: Configuration is a credential config
[aws-sso-creds-helper]: Credential is expired
[aws-sso-creds-helper]: Checking 203f630face956dbe57ecc06395741fe662d446e.json in /Users/user1/.aws/sso/cache/203f630face956dbe57ecc06395741fe662d446e.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/203f630face956dbe57ecc06395741fe662d446e.json
[aws-sso-creds-helper]: Configuration is NOT a credential config
[aws-sso-creds-helper]: Checking 3711b1163b339a7e9a3ed8108c36a8fcc6d85128.json in /Users/user1/.aws/sso/cache/3711b1163b339a7e9a3ed8108c36a8fcc6d85128.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/3711b1163b339a7e9a3ed8108c36a8fcc6d85128.json
[aws-sso-creds-helper]: Configuration is a credential config
[aws-sso-creds-helper]: Credential is expired
[aws-sso-creds-helper]: Checking 4d2d70c5022a0e315c9f33d27fd8aa4961d91645.json in /Users/user1/.aws/sso/cache/4d2d70c5022a0e315c9f33d27fd8aa4961d91645.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/4d2d70c5022a0e315c9f33d27fd8aa4961d91645.json
[aws-sso-creds-helper]: Configuration is a credential config
[aws-sso-creds-helper]: Credential is expired
[aws-sso-creds-helper]: Checking 53715388f88dfbbc1adaf48a5486a05293eb368a.json in /Users/user1/.aws/sso/cache/53715388f88dfbbc1adaf48a5486a05293eb368a.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/53715388f88dfbbc1adaf48a5486a05293eb368a.json
[aws-sso-creds-helper]: Configuration is NOT a credential config
[aws-sso-creds-helper]: Checking 57fcc8a8b15eb43c6db253035baf19558d3a087d.json in /Users/user1/.aws/sso/cache/57fcc8a8b15eb43c6db253035baf19558d3a087d.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/57fcc8a8b15eb43c6db253035baf19558d3a087d.json
[aws-sso-creds-helper]: Configuration is NOT a credential config
[aws-sso-creds-helper]: Checking 7505d64a54e061b7acd54ccd58b49dc43500b635.json in /Users/user1/.aws/sso/cache/7505d64a54e061b7acd54ccd58b49dc43500b635.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/7505d64a54e061b7acd54ccd58b49dc43500b635.json
[aws-sso-creds-helper]: Configuration is a credential config
[aws-sso-creds-helper]: Credential is NOT expired
[aws-sso-creds-helper]: Checking bf3a5d36eb6fe457a102b08904f83d79b76f92c9.json in /Users/user1/.aws/sso/cache/bf3a5d36eb6fe457a102b08904f83d79b76f92c9.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/bf3a5d36eb6fe457a102b08904f83d79b76f92c9.json
[aws-sso-creds-helper]: Configuration is a credential config
[aws-sso-creds-helper]: Credential is expired
[aws-sso-creds-helper]: Checking botocore-client-id-<redacted>.json in /Users/user1/.aws/sso/cache/botocore-client-id-<redacted>.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/botocore-client-id-<redacted>.json
[aws-sso-creds-helper]: Configuration is NOT a credential config
[aws-sso-creds-helper]: Checking botocore-client-id-us-east-1.json in /Users/user1/.aws/sso/cache/botocore-client-id-us-east-1.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/botocore-client-id-us-east-1.json
[aws-sso-creds-helper]: Configuration is NOT a credential config
[aws-sso-creds-helper]: Checking eb12bc71f85121d45077d2d2b6085a6b7815bba9.json in /Users/user1/.aws/sso/cache/eb12bc71f85121d45077d2d2b6085a6b7815bba9.json
[aws-sso-creds-helper]: Reading /Users/user1/.aws/sso/cache/eb12bc71f85121d45077d2d2b6085a6b7815bba9.json
[aws-sso-creds-helper]: Configuration is a credential config
[aws-sso-creds-helper]: Credential is expired
[aws-sso-creds-helper]: Error is an ExpiredCredsError
[aws-sso-creds-helper]: Failed to load SSO credentials for profile1
[aws-sso-creds-helper]: Cached SSO login is expired/invalid, try running `aws sso login` and try again
[aws-sso-creds-helper]: ExpiredCredsError: Cached SSO login is expired/invalid, try running `aws sso login` and try again
    at Object.exports.getSsoCachedLogin (/Users/user1/.config/yarn/global/node_modules/aws-sso-creds-helper/lib/sso-creds.js:41:11)
    at /Users/user1/.config/yarn/global/node_modules/aws-sso-creds-helper/lib/sso-creds.js:94:37
    at Generator.next (<anonymous>)
    at /Users/user1/.config/yarn/global/node_modules/aws-sso-creds-helper/lib/sso-creds.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/user1/.config/yarn/global/node_modules/aws-sso-creds-helper/lib/sso-creds.js:4:12)
    at Object.exports.run (/Users/user1/.config/yarn/global/node_modules/aws-sso-creds-helper/lib/sso-creds.js:91:59)
    at /Users/user1/.config/yarn/global/node_modules/aws-sso-creds-helper/lib/sso-creds.js:103:27
    at Generator.next (<anonymous>)
    at fulfilled (/Users/user1/.config/yarn/global/node_modules/aws-sso-creds-helper/lib/sso-creds.js:5:58)
```

On the other hand, if I were to skip the prompt about session name, it will use the old format of `~/.aws/config`
```
aws configure sso --profile profile1
SSO session name (Recommended): (leave this empty/blank)
WARNING: Configuring using legacy format (e.g. without an SSO session).
Consider re-running "configure sso" command and providing a session name.
SSO start URL [None]: <redacted>
SSO region [None]: <redacted>
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.eu-west-2.amazonaws.com/

Then enter the code:

<redacted>
There are <redacted> AWS accounts available to you.
Using the account ID <redacted>
There are <redacted> roles available to you.
Using the role name "<redacted>"
CLI default client Region [None]: <redacted>
CLI default output format [None]: json

To use this profile, specify the profile name using --profile, as shown:

aws s3 ls --profile profile1
```

And the `~/.aws/config` will look like below 
```
[profile1]
sso_start_url =  <redacted>
sso_region =  <redacted>
sso_account_id =  <redacted>
sso_role_name =  <redacted>
region =  <redacted>
output = json
```
`ssocreds -p profile1` works as expected 
```
[aws-sso-creds-helper]: AWS SSO Creds Helper v1.9.0
[aws-sso-creds-helper]: Getting SSO credentials for profile profile1
[aws-sso-creds-helper]: Successfully loaded SSO credentials for profile profile1
```

If I were to run `aws configure sso --profile profile1` and provided the session name, `~/.aws/config` would look like below
```
[profile1]
sso_start_url = <redacted>
sso_region = <redacted>
sso_account_id = <redacted>
sso_role_name = <redacted>
region = <redacted>
output = json
sso_session = profile1
[sso-session profile1]
sso_start_url = <redacted>
sso_region = <redacted>
sso_registration_scopes = sso:account:access
```

And `ssocreds -p profile1` still worked as it's able to find the required information with `[profile1]` block
```
[aws-sso-creds-helper]: AWS SSO Creds Helper v1.9.0
[aws-sso-creds-helper]: Getting SSO credentials for profile profile1
[aws-sso-creds-helper]: Successfully loaded SSO credentials for profile profile1
```
> @rutomo , thanks for contributing!
> 
> I'm unable to reproduce this with the versions you provided. Can you please re-run with the `--debug` flag and post the output with sensitive data removed?
> 
> Thanks!

When you tried to replicate on your side, did you try with a new profile in `~/.aws/config` file? I noticed that setting up the same profile did not trigger the error because it's able to find the required information. I provided the result of `--debug` flag above.

> @rutomo you can fix your issue by reformatting `.aws/config` to the previous SSO format, feel free to reach out in this chat if you'd like assistance with that (see comment above for context).

Thanks. I actually was able to find a work around as mentioned in my original post similar to what you suggested. During configuration i.e. running `aws configure sso`, as long as I don't specify `SSO session name (Recommended)` i.e. leave it blank. Everything works as expected.

**Comment by ryansonshine** [comment]
Thank you for the detailed bug report, I'll have a fix in to support the new profile format by end of day today.

@all-contributors please add @rutomo for bugs
@all-contributors please add @diogobaltazar for bugs

**Comment by ryansonshine** [comment]
@all-contributors please add @rutomo for bugs

**Comment by ryansonshine** [comment]
@all-contributors please add @diogobaltazar for bugs

**Comment by ryansonshine** [comment]
@all-contributors please add @diogobaltazar for bugs
