### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection when using AWS SSO

### ISSUE THREAD

**Issue by jamesma** [ryansonshine/aws-sso-creds-helper#6]
Hello, thanks for developing this tool, I was trying this out but I encountered the following issue after authenticating on my Chrome browser.

```
❯ ~ aws --version
aws-cli/2.0.57 Python/3.7.4 Darwin/19.6.0 exe/x86_64

❯ ~ ssocreds -p default
[aws-sso-creds-helper]: AWS SSO Creds Helper v1.3.10
[aws-sso-creds-helper]: Getting SSO credentials for profile default
[aws-sso-creds-helper]: Failed to load SSO credentials for profile default
[aws-sso-creds-helper]: Cached SSO login is expired/invalid, try running `aws sso login` and try again
(node:16712) UnhandledPromiseRejectionWarning: ExpiredCredsError: Cached SSO login is expired/invalid, try running `aws sso login` and try again
    at Object.exports.getSsoCachedLogin (/usr/local/lib/node_modules/aws-sso-creds-helper/lib/sso-creds.js:34:11)
    at /usr/local/lib/node_modules/aws-sso-creds-helper/lib/sso-creds.js:80:37
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/aws-sso-creds-helper/lib/sso-creds.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/aws-sso-creds-helper/lib/sso-creds.js:4:12)
    at Object.exports.run (/usr/local/lib/node_modules/aws-sso-creds-helper/lib/sso-creds.js:77:59)
    at /usr/local/lib/node_modules/aws-sso-creds-helper/lib/sso-creds.js:88:27
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/aws-sso-creds-helper/lib/sso-creds.js:5:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16712) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:16712) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I tried `aws sso login` but the issue persists. I never got this working, so any help is appreciated!

**Comment by ryansonshine** [comment]
Thanks for reporting this issue.  Can you email me the contents of your
`~/.aws/config`  so I can take a look?

**Comment by jamesma** [comment]
My `config` contents are like so:

```
[default]
sso_start_url = https://xxx.awsapps.com/start
sso_region = us-west-1
sso_account_id = yyy
sso_role_name = development-swe-role
region = us-west-1
output = json

[profile staging-swe]
sso_start_url = https://xxx.awsapps.com/start
sso_region = us-west-1
sso_account_id = xxx
sso_role_name = staging-swe-role
region = us-west-1
output = json

[profile production-swe]
sso_start_url = https://xxx.awsapps.com/start
sso_region = us-west-1
sso_account_id = yyy
sso_role_name = production-swe-role
region = us-west-1
output = json
```

**Comment by ryansonshine** [comment]
Thanks @jamesma. I plan to add some additional logging for the debug flag but in the interim can you confirm a few things for me:

1. Your operating system
2. Your ability to run `aws sso login` and `aws s3 ls` successfully (without running ssocreds)

**Comment by ryansonshine** [comment]
@jamesma I've published a new version with additional logging for debugging. Please try again adding the `--debug` flag, ie: `ssocreds --debug` and paste the logs.

**Comment by ryansonshine** [comment]
@jamesma I've published a new version with additional logging for debugging. Please update with `npm install -g aws-sso-creds@latest` and run again with the debug flag set `ssocreds --debug` and paste the results.

**Comment by ryansonshine** [comment]
An update has been pushed that should resolve this issue. If it persists please open another.
