### ISSUE TITLE
Does not support [profile PROFILE_NAME] syntax, only [PROFILE_NAME]

### ISSUE THREAD

**Issue by smartin-qb** [ryansonshine/aws-sso-creds-helper#76]
## Current Behavior

Does not support syntax [PROFILE_NAME], only [profile PROFILE_NAME]

If you use a profile setup with  [PROFILE_NAME] syntax you get the following

```
/app/qb-serverless aws-shared_to_dev > ssocreds --profile PROFILE_NAME                                                                            1s root@smartin-qb-serverless-dev 17:50:09
[aws-sso-creds-helper]: AWS SSO Creds Helper v1.10.11
[aws-sso-creds-helper]: Getting SSO credentials for profile PROFILE_NAME
[aws-sso-creds-helper]: Failed to load SSO credentials for PROFILE_NAME
[aws-sso-creds-helper]: No profile found for PROFILE_NAME
[aws-sso-creds-helper]: Run ssocreds with --debug flag for more details.
(node:2511) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
```
## Expected Behavior

To load the credentials for the valid profile

## Steps to Reproduce the Problem

  1. Create a profile with [PROFILE_NAME] syntax which if you do not `aws configure list-profiles` might not show them.
  1. Run `ssocreds --profile PROFILE_NAME`

## Environment

- Version: aws-sso-creds-helper@1.10.11
- Platform: Linux
- Node.js Version: v16.20.0

**Comment by ryansonshine** [comment]
Hi @smartin-qb ,

I have tested configurations with the [profile PROFILE_NAME] syntax and they work as expected. Can you please re-run the command with the `--debug` flag and post your logs?

Thanks

**Comment by smartin-qb** [comment]
Sure, sorry for the accidental edits.

Here is the output 

```
0867039d748a:/# ssocreds --profile test --debug
[aws-sso-creds-helper]: AWS SSO Creds Helper v1.10.10
(node:7) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
[aws-sso-creds-helper]: ===========
[aws-sso-creds-helper]: SYSTEM INFO
[aws-sso-creds-helper]: ===========
[aws-sso-creds-helper]: AWS CLI Version aws-cli/2.13.0 Python/3.11.4 Linux/5.15.49-linuxkit-pr source/aarch64.alpine.3 prompt/off
[aws-sso-creds-helper]: OS linux 5.15.49-linuxkit-pr
[aws-sso-creds-helper]: Node v20.4.0
[aws-sso-creds-helper]: ==============
[aws-sso-creds-helper]: PROFILE CONFIG
[aws-sso-creds-helper]: ==============
[aws-sso-creds-helper]: NOT FOUND
[aws-sso-creds-helper]: Getting SSO credentials for profile test
[aws-sso-creds-helper]: Reading config from /root/.aws/config
[aws-sso-creds-helper]: Full profile name for lookup is profile test
[aws-sso-creds-helper]: Error is NOT an ExpiredCredsError
[aws-sso-creds-helper]: Error is NOT an AwsSdkError
[aws-sso-creds-helper]: Failed to load SSO credentials for test
[aws-sso-creds-helper]: No profile found for test
[aws-sso-creds-helper]: ProfileNotFoundError: No profile found for test
    at exports.getProfile (/usr/local/lib/node_modules/aws-sso-creds-helper/lib/sso-creds.js:85:15)
    at /usr/local/lib/node_modules/aws-sso-creds-helper/lib/sso-creds.js:105:33
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/aws-sso-creds-helper/lib/sso-creds.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/aws-sso-creds-helper/lib/sso-creds.js:4:12)
    at exports.run (/usr/local/lib/node_modules/aws-sso-creds-helper/lib/sso-creds.js:103:59)
    at /usr/local/lib/node_modules/aws-sso-creds-helper/lib/cli.js:37:31
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/aws-sso-creds-helper/lib/cli.js:5:58)
```

**Comment by ryansonshine** [comment]
The syntax for configuration on a named profile is `[profile PROFILE_NAME]`. Is there a specific reason you're configuring your CLI to use a `[PROFILE_NAME]` syntax?

**Comment by ryansonshine** [comment]
`[default]` is the valid syntax for a default profile. Named profiles should be `[profile user1]`.

I'm not sure which tools are using that structure but is it possible you may be thinking of the credential file syntax which is in fact `[default]` `[user1]`?
